apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      containers:
      - name: migration-job
        image: fcabrera01/ccg-migration-job
        command: ["npm",  "run", "migrate"]
        envFrom:
          - configMapRef:
              name: open-ims-config-map
          - secretRef:
              name: open-ims-secrets
        env:
          - name: PGPASSWORD
            value: "$(POSTGRES_PASSWORD)"
          - name: PGUSER
            value: "$(POSTGRES_USER)"
          - name: PGDATABASE
            value: "$(POSTGRES_DB)"
          - name: JOB_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      restartPolicy: Never
  activeDeadlineSeconds: 120
  backoffLimit: 5