FROM node:18.17.0-alpine3.18

EXPOSE 3000
USER node 

RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node ./ ./
RUN npm run build

CMD ["npm", "run", "dev"]