apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-reader
rules:
- apiGroups: ["batch"] # "" indicates the core API group
  resources: ["pods", "services", "deployments", "jobs"]
  verbs: ["get", "watch", "list"]