FROM node:18.17.0-alpine3.18 as builder

WORKDIR /home/node/app

COPY ./package.json ./
RUN npm install
COPY ./ ./
RUN npm run staging

# Slimmed production image
FROM nginx:1.24.0

EXPOSE 5000

COPY --from=builder /home/node/app/dist /usr/share/nginx/html
COPY /nginx/default.conf /etc/nginx/conf.d/default.conf

# TODO Get rid of this staging environment, instead when trying to run prod-local/staging just use the "dev" VITE_MODE profile variables since they will be the same.....